User tinyproxy
Group tinyproxy
Port 8888
Listen 10.20.1.10
Timeout 600
LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Warning
MaxClients 20
Allow 10.20.2.10
Allow 10.20.2.20
ConnectPort 443
DisableViaHeader Yes
